services:
  server:
    build:
      context: ./server
    ports:
      - "3003:3003"
    environment:
      PORT: "3003"
      DATABASE_URL: postgresql://postgres:password@db:5432/myrelay_db
    volumes:
      - ./server:/app
      - /app/node_modules
    command: bun run dev
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myrelay_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/src/db:/db:ro

volumes:
  postgres_data:
